#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='emacsclient -nw'
export VISUAL='emacsclient -nw'
export PAGER='less'
export DELIVERY_SSH_PUB_KEY=~/.ssh/sfalcon.pub
#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home

# Set the list of directories that Zsh searches for programs.
path=(
  /opt/delivery-cli/bin
  /usr/local/{bin,sbin}
  ~/bin
  ~/perl5/bin
  ~/oc/code/opscode/concrete 
  /usr/local/bin 
  /usr/local/sbin
  /opt/homebrew-cask/Caskroom/emacs/24.5-1/Emacs.app/Contents/MacOS/bin
  /usr/local/texlive/2015basic/bin/x86_64-darwin
  $JAVA_HOME
  $path
)

# nvm
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# perl
eval $(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)

export GOPATH=/Users/seth/src/godev
export GOBIN=/Users/seth/src/godev/bin
##export GOROOT=/Users/seth/src/godev/bin

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

/usr/local/bin/keychain -Q -q sfalcon sf_github

if [[ -f ~/.keychain/$HOST-sh ]]; then
    source "$HOME/.keychain/$HOST-sh"
fi

if [[ -f ~/.keychain/$HOST-sh-gpg ]]; then
    source "$HOME/.keychain/$HOST-sh-gpg"
fi

source "$HOME/.zprezto/runcoms/secrets"

source "$HOME/.zprezto/runcoms/chef-shell-init"
