#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='emacsclient -nw'
export VISUAL='emacsclient -nw'
export PAGER='less'
export DELIVERY_SSH_PUB_KEY=~/.ssh/sfalcon.pub
#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  ~/bin 
  ~/Erlang/17.0/bin 
  ~/oc/code/opscode/concrete 
  /usr/local/bin 
  /usr/local/sbin 
  /Applications/Emacs.app/Contents/MacOS/bin 
  /usr/local/share/python 
  /usr/local/Cellar/python/2.7.2/bin 
  /usr/local/texlive/2007/bin/i386-darwin 
  /usr/texbin 
  $JAVA_HOME   
  $path
)

source /usr/local/share/chruby/chruby.sh
chruby 2.1.2

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

/usr/local/bin/keychain -Q -q opscode-platform-20100217 \
                              opscode-preprod-20101208 \
                              sfalcon \
                              sf_github

if [[ -f ~/.keychain/$HOST-sh ]]; then
    source "$HOME/.keychain/$HOST-sh"
fi

if [[ -f ~/.keychain/$HOST-sh-gpg ]]; then
    source "$HOME/.keychain/$HOST-sh-gpg"
fi

