#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias cdeliv='cd ~/oc/code/opscode/delivery'
alias cod='cd ~/oc/code/opscode/omnibus-delivery'
alias cweb='cd ~/oc/code/opscode/delivery-web'
alias ecn='emacsclient -n'
alias e='emacsclient -n'
alias en='emacsclient -nw'

