#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias cdeliv='cd ~/oc/code/opscode/delivery'
alias ccli='cd ~/oc/code/opscode/delivery-cli'
alias cod='cd ~/oc/code/opscode/omnibus-delivery'
alias cweb='cd ~/oc/code/opscode/delivery-web'
alias ecn='emacsclient -n'
alias e='emacsclient -n'
alias en='emacsclient -nw'
# alias hab_vm='docker-machine create -d vmwarefusion --vmwarefusion-memory-size 8000 --vmwarefusion-cpu-count 4 --vmwarefusion-disk-size 4000 default; eval $(docker-machine env default)'
# alias hab_vm_create='docker-machine create -d virtualbox --virtualbox-memory "8000" --virtualbox-cpu-count "4" --virtualbox-disk-size "4000" default'
# alias hab_vm_setup='eval $(docker-machine env default)'

PERL_MB_OPT="--install_base \"/Users/seth/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/seth/perl5"; export PERL_MM_OPT;

